### ISSUE TITLE
Unable to resize TST width

### ISSUE THREAD

**Issue by foxhoundsk** [hakan-demirli/Firefox_Custom_CSS#6]
I'm using [Tree Style Tab](https://addons.mozilla.org/en-US/firefox/addon/tree-style-tab/) on Firefox 103.0.2, and the OS is Linux.

The resize icon did appear when hovering onto the edge of TST. However, draging the edge doesn't resize TST's width.

As a side note, IIUC, it is now at the narrowest width:
![image](https://user-images.githubusercontent.com/19415202/187489283-6705397d-f78a-486a-b7f4-ef64e63e12ff.png)

Thanks!

**Comment by foxhoundsk** [comment]
I'm now managed to resize the tab by commenting out the following in `userChrome.css`:
```
#sidebar,
  #sidebar-header {
    position: relative !important;
    min-width: var(--sidebar-min-width) !important;
    max-width: var(--sidebar-min-width) !important;
  transition: .1s ease .1s;
    z-index:1;
  }
```

I still can't figure how this limits the resize operation, could anyone give me a hint?

Thanks!

**Comment by foxhoundsk** [comment]
I just found that maybe the following is suppose to narrowing the TST width when the focus is not in the sidebar:
```
  #sidebar,
  #sidebar-header {
    position: relative !important;
    min-width: var(--sidebar-min-width) !important;
    max-width: var(--sidebar-min-width) !important;
  transition: .1s ease .1s;
    z-index:1;
  }

  #sidebar-box:hover :-moz-any(#sidebar,#sidebar-header) {
    min-width: var(--sidebar-visible-width) !important;
    max-width: var(--sidebar-visible-width) !important;
    margin-right: calc((var(--sidebar-visible-width) - var(--sidebar-min-width)) * -1) !important;
    z-index:1;
    position: relative !important;
  transition: .21s ease 3.20s;
  }
```

However, with this, I can't adjust the TST width while having this feature.

Is it possible that I can adjust the width while keeping the auto sizing of sidebar feature enabled?

Thanks!

**Comment by hakan-demirli** [comment]
Since there were some bugs that I forgot, I disabled the resize feature by limiting the max-min width of the sidebar. But, let me tell you everything I know about the code which I have stolen from someone else.

As you have noticed by default the size of the sidebar is fixed to [ `--sidebar-min-width`.](https://github.com/hakan-demirli/Firefox_Custom_CSS/blob/d354c4083d3e6b2823aac22964a0964bbff81371/userChrome.css#L4)
`min-width` and `max-width` properties are set to the same variable. Hence, you can't drag it to increase its size.

https://github.com/hakan-demirli/Firefox_Custom_CSS/blob/d354c4083d3e6b2823aac22964a0964bbff81371/userChrome.css#L49-L56

You can create another variable `--sidebar-max-width` and set it to something higher. Lets say 200px.
Assign it to the max-width.
```css
  #sidebar,
  #sidebar-header {
    position: relative !important;
    min-width: var(--sidebar-min-width) !important;
    max-width: var(--sidebar-max-width) !important;
  transition: .1s ease .1s;
    z-index:1;
  }
```
Now you can resize the sidebar by mouse as long as it doesn't exceed these two variables.
Also if you hover your mouse over the sidebar for 3 seconds. It will expand or shrink to reach the `--sidebar-visible-width`, which is 162px.

You can also change the hover time by adjusting this.
https://github.com/hakan-demirli/Firefox_Custom_CSS/blob/d354c4083d3e6b2823aac22964a0964bbff81371/userChrome.css#L64
Or you can just disable the mouse hover event by removing the whole block.

**Comment by foxhoundsk** [comment]
@hakan-demirli Got it, thank you for the detailed explanation.
